name: Bug report
description: Create a report to help us improve
title: "[BUG]"
labels: bug
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: input
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please list the steps to reproduce the issue
      placeholder: "1. Go to the page\n2. Click on button"

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happened?

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - Critical
        - Major
        - Minor

